spring.application.name=app

spring.data.redis.host=xeubiart-cache
spring.data.redis.port=6379

spring.profiles.active=${PROFILE}

spring.datasource.url=jdbc:postgresql://db:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

grpc.server.permit-keep-alive-without-calls=true
grpc.server.permit-keep-alive-time=10s

grpc.server.port=50051

app.cors.allowed-origins=https://xeubiart.com

server.servlet.session.cookie.name=SESSION
server.servlet.verification.cookie.name=VERIFICATION

spring.session.redis.repository-type=indexed