logging.level.io.grpc=DEBUG

grpc.server.port=50052
spring.data.redis.host=localhost

spring.jpa.hibernate.ddl-auto=create-drop

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

app.cors.allowed-origins=http://localhost:9999,http://localhost:8080