server.port=8080
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.config.import=optional:file:.env[.properties]

app.cors.allowed-origins=http://localhost:9999,http://localhost:8080