spring.application.name=backend
spring.config.import=optional:file:.env[.properties]

app.feature.send-emails=${ENABLE_EMAILS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.resend.com
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.default-encoding=UTF-8

spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}

app.cors.allowed-origins=http://localhost