server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
logging.level.root=INFO
server.servlet.session.cookie.path=/
spring.session.jdbc.initialize-schema=always

app.cors.allowed-origins=https://xeubiart.com